<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/17
 * Time: 1:22
 */

namespace common\controllers;

use Yii ;
use yii\web\Controller ;


class BaseController extends Controller
{
    /**
     * 定义错误处理页面
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->params['userErrDef']         = [
            'redirectUrl'           => 'site/index',
            'redirectName'          => '首页',
        ] ;
        Yii::$app->getErrorHandler()->errorAction  = 'public/error';
    }

    /**
     * 成功跳转页面
     * @param $wemsg
     * @param null $site
     * @param int $second
     * @return string
     */
    protected function success($wemsg, $site=null, $second=3)
    {
        return $this->jump($wemsg, $site, $second, 1) ;
    }

    /**
     * 失败跳转页面
     * @param $wemsg
     * @param null $site
     * @param int $second
     * @return string
     */
    protected function error($wemsg, $site=null, $second=3)
    {
        return $this->jump($wemsg, $site, $second, 0) ;
    }

    /**
     * 私有方法
     * @param string $wemsg
     * @param string $site
     * @param int $second
     * @param int $success
     * @return string
     */
    private function jump($wemsg='', $site='site/index', $second=3, $success=0)
    {
        /**
         * @app ,frontend ,backend
         *
         */
        return $this->renderPartial('@app/views/public/jump',[
            'name'          => '跳转页面',
            'jumpUrl'       => $site ,
            'wemsg'         => $wemsg ,
            'waitSecond'    => $second,
            'success'       => $success // 0为错误页面， 1为成功页面
        ]);
    }

}